jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest]
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.4
      - run: |
          haxe -version
          haxelib install hxnodejs
